overrides:
  ceph:
    fs: xfs
    conf:
      osd:
        osd objectstore: seastore
        debug seastore: 20
        debug seastore onode: 20
        debug seastore odata: 20
        debug seastore ompap: 20
        debug seastore tm: 20
        debug seastore t: 20
        debug seastore cleaner: 20
        debug seastore epm: 20
        debug seastore lba: 20
        debug seastore fixedkv tree: 20
        debug seastore cache: 20
        debug seastore journal: 20
        debug seastore device: 20
        debug seastore backref: 20
